### ISSUE TITLE
Diary Component on MiniApp Screen is not working!!!

### ISSUE THREAD

**Issue by IAmTester35** [MaiThanhNam141/PabCare#5]
I'm encountering an issue with the Diary Component on the MiniApp Screen. The exact cause of the bug is unclear, but it seems to be related to the useEffect hook. The error message appears as soon as the app is opened, suggesting that the issue might be within the initial rendering or data fetching process.

**Comment by MaiThanhNam141** [comment]
Thank you for reporting this issue. We understand the impact this bug might have on the user experience and appreciate your patience as we investigate the matter.
Currently, we are facing resource constraints and are unable to prioritize a fix for this issue immediately. We are committed to addressing all reported bugs and will strive to resolve this one as soon as possible.
We apologize for any inconvenience this may cause and will keep you updated on the progress of the fix.
**Thank you for your understanding.**

**Comment by MaiThanhNam141** [comment]
Diary released on 0.9.4 version.
